name: mslotwinski_2048
description: Simple 2048 app for iOS and Android written in flutter.
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: lib/assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic

        - asset: lib/assets/fonts/Rubik-Regular.ttf
        - asset: lib/assets/fonts/Rubik-Italic.ttf
          style: italic
        
        - asset : lib/assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset : lib/assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic

        - asset : lib/assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset : lib/assets/fonts/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: lib/assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic

        - asset : lib/assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset : lib/assets/fonts/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: lib/assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset : lib/assets/fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic


    # - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
